name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install pipenv
      run: |
        python -m pip install pipenv

    - name: Install Dependencies
      run: |
        cd starter/backend
        pipenv install

    - name: Lint Code
      run: |
        cd starter/backend
        pipenv run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install pipenv
      run: |
        python -m pip install pipenv

    - name: Install Dependencies
      run: |
        cd starter/backend
        pipenv install

    - name: Run Tests
      run: |
        cd starter/backend
        pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        cd starter/backend
        pipenv install

    - name: Lint Code (Fail Workflow on Lint Failure)
      run: |
        cd starter/backend
        pipenv run lint-fail

    - name: Build backend (Python example)
      run: |
        cd starter/backend
        ls -R

# Add other steps as needed for your build and test process
