name: Frontend CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install and configure aws-iam-authenticator
      run: |
        curl -X GET -L https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.6.2/aws-iam-authenticator_0.6.2_linux_amd64 -o aws-iam-authenticator
        chmod +x ./aws-iam-authenticator
        ./aws-iam-authenticator help
        ./aws-iam-authenticator version
        
     
