name: Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm install

    - name: Lint Code
      run: |
        cd starter/frontend
        npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm install

    - name: Run Tests
      run: |
        cd starter/frontend
        npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]  # This ensures 'build' only runs if 'lint' and 'test' jobs succeed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd starter/frontend
        npm install

    - name: Build Frontend
      run: |
        cd starter/frontend
        npm run build

# Add other steps as needed for your build and test process


# Add other steps as needed for your build and test process

# name: Continuous Integration

# on:
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'starter/frontend/**'
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16'
      
#       - name: Debug working directory
#         run: |
#           cd starter/frontend
#           ls -R

# name: Continuous Integration

# on:
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'starter/frontend/**'
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
      
#     - name: Debug working directory
#       run: |
#         ls -R
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: 
#         - actions/checkout@v3
#         - actions/setup-node@v3
#       with:
#         node-version: 16

#     - name: Debug working directory
#       # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
#       run: |
#         ls -R

#     - name: Install Dependencies
#       run: npm install

#     - name: Build Frontend
#       run: npm run build

    # Add other steps as needed for your build and test process
